### ISSUE TITLE
BAM files with : in header

### ISSUE THREAD

**Issue by pascalg** [a-bioinformatician/BreaKmer#1]
Hi,

My BAM file has additional ":" in the header, so the script crashes, as exacltly 5 fields are expected.

  File "breakmer.py", line 104, in <module>
    r.run(tic)
  File "/home/pgellert/bin/BreaKmer-master/sv_processor.py", line 195, in run
    if not trgt.get_sv_reads() :
  File "/home/pgellert/bin/BreaKmer-master/sv_processor.py", line 471, in get_sv_reads
    self.clean_reads('norm')
  File "/home/pgellert/bin/BreaKmer-master/sv_processor.py", line 684, in clean_reads
    self.files['%s_cleaned_fq'%type], self.cleaned_read_recs[type], self.read_len = get_fastq_reads(self.files['%s_cleaned_fq'%type], self.sv_reads[type])
  File "/home/pgellert/bin/BreaKmer-master/utils.py", line 372, in get_fastq_reads
    for header,seq,qual in FastqFile(fn) : 
  File "/home/pgellert/bin/BreaKmer-master/utils.py", line 926, in next
    inst,lane,tile,x,y_end = header.split(':')
ValueError: too many values to unpack

**Comment by ryanabo** [comment]
Thanks for sending me this! I will work on this fix. Can you send me a
couple of lines in your BAM?

Ryan

**Comment by pascalg** [comment]
Thanks, Ryan. Here are some lines:

`HWI-ST720:137778324:D22C0ACXX:6:1306:8503:19725 163     1       10008   0       100M    =       10339   430     AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACC    CCCFFFFFHHHHHJJJJJIIJJJJJJJJJJJJJJJJHIIJJJJJBHIIIIFHIIAEGGIFEHHHFFDCDEDCACDDDDAC<ABDC?A?<A3<?<ABC388     X0:i:331        MD:Z:100        PG:Z:MarkDuplicates.3   RG:Z:2892445281 XG:i:0  AM:i:0  NM:i:0  SM:i:0  XM:i:0  XO:i:0  XT:A:R
HWI-ST720:137778324:D22C0ACXX:6:1215:7300:35023 65      1       10023   20      100M    18      78016187        0       CCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTACCCTAACCCTAA    CCCFFFFFHHGHHJJJJJJJJJJJJJIJJJJJFIJJJJCHHIJJIJJJJIGIJJJJJIJJHHH@DDBDEEEEEDD5=AB@A5<BDDD(8AB39<ABD<A#     X0:i:1  X1:i:2  XA:Z:12,-95581,100M,2;1,+10017,100M,2;  MD:Z:86A13      PG:Z:MarkDuplicates.3   RG:Z:2892445281 XG:i:0  AM:i:20  NM:i:1  SM:i:20 XM:i:1  XO:i:0  XT:A:U
HWI-ST720:137778324:D22C0ACXX:5:1204:3142:48450 69      1       10055   0       *       =       10055   0       TTAGGGTTAGGGTGAGGGTTAGGGTGAGGGTGAGGGTTAGGGTGAGGGTGAGGGTTAGGGTGAGGGTGAGGGTTAGGGTGAGGGTGAGGGTTAGGGTTAG    CCCFFFDDHHHHDFHHIJAFHHAHEBHGHG?F=FD=0?F@FG*<B@B7;F@EHEEEEEFF75;ABA;?AAA?55?595,8A?AB288?BB?A<?ABCBB<     PG:Z:MarkDuplicates     RG:Z:2892445465
HWI-ST720:137778324:D22C0ACXX:5:1204:3142:48450 137     1       10055   15      60M40S  =       10055   0       TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAAACCTAACCCTCACCCTACCCCTAAACCTAACCCTCACC    @CCFFFEFHHDHFBHGGBFGEECFHHAGGG@CHDGGCEHIIGI>FD;CH)8@G(-=1AB#########################################     X0:i:1  X1:i:6  XC:i:60 MD:Z:60 PG:Z:MarkDuplicates     RG:Z:2892445465 XG:i:0  AM:i:0  NM:i:0  SM:i:15 XM:i:0  XO:i:0  XT:A:U
HWI-ST720:137778324:D22C0ACXX:5:2207:11909:40241        73      1       10066   16      69M31S  =       10066   0       CTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCCAACCCTAACCCTAACCCTAACCCTCTAACCCTACCCCCCTAACCC    @CCDFDDDHGHHGJJJJJJJIJJJIJIJJGIGGFHGIEGCAAG7?DH68BCEHCEG@EF/(.;@A62@################################     X0:i:1  X1:i:5  XC:i:69 MD:Z:54T14      PG:Z:MarkDuplicates     RG:Z:2892445465 XG:i:0  AM:i:0  NM:i:1  SM:i:16 XM:i:1  XO:i:0   XT:A:U
HWI-ST720:137778324:D22C0ACXX:5:2207:11909:40241        133     1       10066   0       74M26S  =       10066   0       GTGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGAGGGTTAGGGTTAGAGGGTTAGGGTTAGGGGGGTAGGGTTAGAGGGTTAGG    @@@DDFFDHFHFHIGFHIGHGFEAGIJ?FFHHI9CAGHFD>BFHHB@=B48BF-=663@).623?DF5;=B@?###########################     XC:i:74 PG:Z:MarkDuplicates     RG:Z:2892445465
HWI-ST720:137778324:D22C0ACXX:6:2212:3000:37796 99      1       10188   9       47M53S  =       10376   256     ACCCTAACCCGAACCCTAACCCTAACCCGAACCCTAACCCGAACCCCAAACCCCACCCCCCACCCCCACCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC    CCCFFFFFHHHHHJJJJJJJJJIIIJJJHIJJJJJJIJJJ@EE8=D######################################################     X0:i:20 X1:i:0  XC:i:47 MD:Z:10T17T11T6 PG:Z:MarkDuplicates.3   RG:Z:2892445281 XG:i:0  AM:i:0  NM:i:3  SM:i:0  XM:i:3  XO:i:0  XT:A:R
HWI-ST720:137778324:D22C0ACXX:5:1103:13566:13795        73      1       10267   0       18M1D55M27S     =       10267   0       TAACCCTAACCCTAACCCAACCCCAACCCCAACCCCCACCCCAACCCCAACCCCAACCCTAACCCCTAACCCCAACCCCAACCCTAACCCTAACCCCAAA     CCCFFFFFHHHHDGIIIIGHEHII1??DGH;)0?FH0;;@FF;@5;BH;?;?AC;5(9@(5?5<BB72<8?B############################    X0:i:2  X1:i:0  XA:Z:1,-249240340,55M1D18M,3;   XC:i:73 MD:Z:18^T18A35T0        PG:Z:MarkDuplicates     RG:Z:2892445465  XG:i:1  AM:i:0  NM:i:3  SM:i:0  XM:i:2  XO:i:1  XT:A:R
HWI-ST720:137778324:D22C0ACXX:5:1103:13566:13795        133     1       10267   0       68M32S  =       10267   0       GTTTAGGGTTTAGGGTTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGGTTAGGGGTTAGGGGTTAGGGTTGGGGTTGGGGTTAGGGTTGGGGGTTGGGGTG    @@BFFFFFHHHHHIIAGHHGIJEHGHII?EDHII?D@@FGBGCHIFI;068@EG@8(=AED,'(;@?#################################     XC:i:68 PG:Z:MarkDuplicates     RG:Z:2892445465
HWI-ST720:137778324:D22C0ACXX:5:2308:17431:53297        117     1       10329   0       67M33S  =       10329   0       GGGTTAGGGTTAGGGTTAGAGGGTTAGGGTTAGAGGGTTATGGTTAGAGGGTTAGGGTTAGAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGGGTTA    ##################################?:E??7)EHC@AC;@=88)B=>FDD?DEGBF@EGG@FA?88IHEADGIHIEIFHHHHGFFFFFCCC     XC:i:67 PG:Z:MarkDuplicates     RG:Z:2892445465`

**Comment by ryanabo** [comment]
This issue has been resolved in the latest release v0.0.2.
