### ISSUE TITLE
Documentation/Help issues

### ISSUE THREAD

**Issue by dgaston** [a-bioinformatician/BreaKmer#11]
Current documentation on the web is out of date (no examples include the fncCmd needed as the first argument ie run, start_blat_server, prepare_reference_data).

Help output is also out of date. Instead of prepare_reference_data the option provided is prepare_reference_kmers when you run breakmer.py with no arguments.

Suggestion for enhancement would be to provide a help message if the user executes breakmer.py -h instead of saying it is not one of the appropriate commands to run. This is a standard user behaviour.

**Comment by ryanabo** [comment]
You are correct. The document was outdate. I have now updated this and made the necessary changes so that the breakmer.py -h works as intended to provide more details as to how to run the program.
