### ISSUE TITLE
NameError: global name 'binary' is not defined

### ISSUE THREAD

**Issue by apastore** [a-bioinformatician/BreaKmer#14]
Hi I would like to run Breakmer and validate some results. I am just sticking since I get in the very beginning this error. Cutadapt and Jellifish are running and in my PATH.

Thanks for your help
Alessandro 

python ~/bin/breakmer/breakmer.py run -c breakmer.cfg
Traceback (most recent call last):
  File "/cbio/cslab/home/pastore/bin/breakmer/breakmer.py", line 70, in <module>
    RUN_TRACKER = breakmer_analysis.RunTracker(params.ParamManager(PARSER.parse_args()))
  File "/cbio/cslab/home/pastore/bin/breakmer/breakmer/params.py", line 51, in **init**
    self.set_params(arguments)
  File "/cbio/cslab/home/pastore/bin/breakmer/breakmer/params.py", line 103, in set_params
    self.check_binaries()  # Check if Jellyfish and Cutadapt work.
  File "/cbio/cslab/home/pastore/bin/breakmer/breakmer/params.py", line 201, in check_binaries
    self.set_param(binary, binaryCheck)  # Store the result in the opts dictionary.
NameError: global name 'binary' is not defined

-bash-4.1$ jellyfish --version
jellyfish 2.2.3
-bash-4.1$ jellyfish --help
Usage: jellyfish <cmd> [options] arg...
Where <cmd> is one of: count, bc, info, stats, histo, dump, merge, query, cite, mem, jf.
Options:
  --version        Display version
  --help           Display this message

-bash-4.1$ cutadapt
cutadapt version 1.8.3
Copyright (C) 2010-2015 Marcel Martin marcel.martin@scilifelab.se

cutadapt removes adapter sequences from high-throughput sequencing reads.

Usage:
    cutadapt -a ADAPTER [options] [-o output.fastq] input.fastq

For paired-end reads:
    cutadapt -a ADAPT1 -A ADAPT2 [options] -o out1.fastq -p out2.fastq in1.fastq in2.fastq

Replace "ADAPTER" with the actual sequence of your 3' adapter. IUPAC wildcard
characters are supported. The reverse complement is _not_ automatically
searched. All reads from input.fastq will be written to output.fastq with the
adapter sequence removed. Adapter matching is error-tolerant. Multiple adapter
sequences can be given (use further -a options), but only the best-matching
adapter will be removed.

Input may also be in FASTA format. Compressed input and output is supported and
auto-detected from the file name (.gz, .xz, .bz2). Use the file name '-' for
standard input/output. Without the -o option, output is sent to standard output.

Some other available features are:
- Various other adapter types (5' adapters, "mixed" 5'/3' adapters etc.)
- Trimming a fixed number of bases
- Quality trimming
- Trimming colorspace reads
- Filtering reads by various criteria

Use "cutadapt --help" to see all command-line options.
See http://cutadapt.readthedocs.org/ for full documentation.

**Comment by ryanabo** [comment]
I am sorry for your troubles with the software! Thank you for reporting this bug. It is now fixed in the master branch. Please pull this down again and test. Let me know if there are any other issues.
