### ISSUE TITLE
reformat the <analysis_name>_svs.all.out file

### ISSUE THREAD

**Issue by apastore** [a-bioinformatician/BreaKmer#16]
Hi Ryan, I am trying to detect SV variant using BreaKmer,I have just two question regarding the out file. 

BreaKmer is generating only <analysis_name>_svs.all.out and <analysis_name>_svs.out. In those file I have only Indels, an dI was expecting to have file with trl,inv_rearrangement,td_rearrangement in their name. I ma doing something wrong?

The out file also have a new line character after the Contig_sequence field and this make the output non easy to read. could this be fix?

Thanks a lot for you support
Alessandro

p.s. I can send to you my output file if you need

**Comment by ryanabo** [comment]
Hi Alessandro,

For your first question regarding the output file names. The naming of the
output files has been changed. Now there are only two output files that are
generated - which are the two you are now observing. All the variant types
will be output in these. The "_svs.all.out" contains all the variant calls,
and the "_svs.out" file contains variants that have passed the basic
filtering checks.

As for the second issue regarding the new line character. I will check into
this today and get a fix out ASAP.

I will write when it is complete.

Best,

Ryan

**Comment by apastore** [comment]
Thanks Ryan,

I was sure that it was a change but i just want to double check since I just have indles in the calls and no sv...

**Comment by ryanabo** [comment]
Can you send me an example of your output file where there is a new line
character after the Contig_sequence field. I am having a hard time finding
this formatting.

Ryan

**Comment by apastore** [comment]
Sure! This is one example. If you do not get the attached file just let me know I will put in a google folder
Thanks for your help!

**Comment by ryanabo** [comment]
No attachment.

**Comment by apastore** [comment]
I have send it to your gmail now

**Comment by ryanabo** [comment]
I apologize for the delay in this. I have fixed this issue and release in master branch. Let me know if there are any other issues.

**Comment by apastore** [comment]
Thanks!
