### ISSUE TITLE
No reads processed/No Output

### ISSUE THREAD

**Issue by bcolb** [a-bioinformatician/BreaKmer#18]
I've run Breakmer on the example data without any issues. I'm now trying to run it on a few of my own samples and am not getting any output.

The samples do run to completion but there is no output at the end. I think I may have identified where the problem is at but am not sure as to the cause. Looking in the data folder for each targeted gene, I get some files that appear to have processed fine containing data, and some that are empty.

For example, for ALK I get the following files in targets/ALK/data/, each 1M in size:
- ALK_sv_reads.bam
- ALK_sv_reads.sorted.bam
- ALK_sv_reads.sorted.bam.bai
- ALK_sv_sc_seqs.fa

Meanwhile the following files are empty with 0M:
- ALK_sv_reads_cleaned.fastq
- ALK_sv_reads_cleaned_filtered.fastq
- ALK_sv_reads.fastq

Since the same thing happens with each targeted gene, I'm assuming that the issue is not specific to a single gene but to the entire sample or, more likely, my configuration. 

Looking at the logs it seems that the issue is might be popping up either while 'cleaning reads' or 'writing clean reads'.

Any thoughts on what might be causing this?

Thanks in advance.

**Comment by ghost** [comment]
Hi Brice,

I apologize for the issues you are having in using this. Can you specify what kind of sequence data you have and how it was aligned to the reference?

Ryan

**Comment by bcolb** [comment]
Thanks for the quick response Ryan.

These are tumor tissue samples sequenced with an Illumina Nextseq and aligned using BWA against hg19. 

Brice

**Comment by ghost** [comment]
Hi Brice,

Could you grab a set of reads from one of the regions of interest and save
in a bam file to help me diagnose?

Best,

Ryan

**Comment by bcolb** [comment]
Hi again Ryan,

Yes I can put together a bam file for you to see if you experience the same issues. Where should I send it?

Best,

Brice

**Comment by ghost** [comment]
You can send it to ryan.abo@gmail.com, thanks Brice.

Ryan

**Comment by bcolb** [comment]
It turns out that the issue was resolved by updating to a newer version of BreaKmer. I had been running the master branch previously, but switching to a newer release version (a separate branch in this repo) fixed this issue for me.

Thanks for the help Ryan.
