### ISSUE TITLE
Issue running the example

### ISSUE THREAD

**Issue by radaniba** [a-bioinformatician/BreaKmer#20]
Hello Breakmer dev

I am trying to run the example provided in the repo, after personalizing the brakmer.cfg I tried running the do as below, but got that isue

```
python breakmer.py example_data/breakmer.cfg
usage: breakmer.py [options]
breakmer.py: error: argument fncCmd: invalid choice: 'example_data/breakmer.cfg' (choose from 'run', 'start_blat_server', 'prepare_reference_data')
```

Anything you missed in the doc maybe ?

**Comment by mducar** [comment]
Hi,

It looks like you left out the "run" from the command line.  I assume by the other ticket you opened you already resolved this one?

**Comment by radaniba** [comment]
Yes you're right.

I think you need to update the readme file as well as I just tried to follow your recommendation at first place.

Thanks for getting back to me
