### ISSUE TITLE
Which production version is the latest ?

### ISSUE THREAD

**Issue by radaniba** [a-bioinformatician/BreaKmer#23]
Hello

I am looking at the branches here and the newer branches look like patches not a full package, is that correct ?

Can you please let me know is the master branch is the one on production ?

A note in the readme file will be more than helpful

Thank you

**Comment by mducar** [comment]
Hi,

Thanks for the suggestion about updating the readme to make the versions more clear.

The release titled "CCGD_Profile_Production" (v.0.0.6) is the version currently being used at the Center for Cancer Genome Discovery (DFCI) and the Profile project (BWH/DFCI).  That version wasn't initially checked into GitHub but was tracked locally.

As we transitioned our code to GitHub, a few more releases were pushed out -- the most recent being v0.0.7 with a refactored code base.  This release has not been fully vetted and validated for use in our internal pipelines.

**Comment by radaniba** [comment]
was there any major update from the master branch ?

**Comment by mducar** [comment]
The master branch is basically the same as the v0.0.7 prototype release.   A minor change to the readme and the copyright notices were fixed.  But other than that they are the same.

**Comment by radaniba** [comment]
Thank you for your response.
