### ISSUE TITLE
Translocations not called?

### ISSUE THREAD

**Issue by signy-chow** [a-bioinformatician/BreaKmer#29]
Hello, 

After running breakmer with a sample with known translocations, I have and output folder with a subfolder for each exon, which contains sorted reads in bam files, (tree below):

> ├── TRAF3_EXON_12
> │   ├── TRAF3_EXON_12_contig89_reads.bam
> │   ├── TRAF3_EXON_12_contig89_reads.sorted.bam
> │   ├── TRAF3_EXON_12_contig89_reads.sorted.bam.bai
> │   ├── TRAF3_EXON_12_contig89_svs.out
> │   ├── TRAF3_EXON_12_discreads.out
> │   └── TRAF3_EXON_12_svs.out
> ├── TRAF3_EXON_3
> │   └── TRAF3_EXON_3_discreads.out
> ├── TRAF3_EXON_6
> │   └── TRAF3_EXON_6_discreads.out

Each of the _svs.out files gives the coordinates of indels which look like they can be found in the bam files. It seems that the _discreads.out files contain the structural variants (large inserts and translocations) that I am looking for but there is no sorted bam file to go with these. 

The documentation seems to indicate that there should be a bam file output as well as a folder for each variant - is this correct? If so, what is preventing these from being generated?

I have no error messages in my log -- it seems to complete properly (below):

> breakmer.assembly.assembler - INFO - Initiating kmer xxxxxxxxxxxx, found in 16 reads
> breakmer.assembly.contig - DEBUG - 0 kmers left to check
> breakmer.assembly.contig - INFO - Contig done with contig seq xxxxxxx Supported by 2 read(s).
> breakmer.assembly.contig - INFO - Read IDs: xxxxxxxxxxxxxxxx
> breakmer.assembly.assembler - INFO - Contig did not meet the read count threshold 2, with 2 or contig length (151) < readLen (151)
> breakmer.processor.target - INFO - Resolving structural variants from 0 kmer clusters
> breakmer.processor.target - INFO - Writing TRAF3_EXON_9 discordant read cluster result file /mnt/work1/users/xxxxxxxxxxxxxxxxxxxx
> breakmer.processor.analysis - INFO - Writing "Breakmer.JJN3.14Jun16_onlyMAX.NF.TRAF" aggregated results files: all result - xxxxxxxxxxx"_svs.all.out and filtered results - /mnt/work1/users/xxxxxxxxxxxxxxxxxxxxxx_svs.out
> breakmer.processor.analysis - INFO - Writing "xxxxxxxxxxxxx" aggregated results file /mnt/work1/users/xxxxxxxxxxxxxxx_discreads.out
> breakmer.processor.analysis - INFO - Analysis complete in 2489.59

Thanks for any insights!

**Comment by mducar** [comment]
Hi,
It looks like you are using the unstable code in the master branch or one of the prototype releases.  We've identified several issues with this code and recommend everyone use the release 0.0.6 version of BreaKmer.

**Comment by signy-chow** [comment]
Hi, Matt,

Thank you for your quick response. I have a couple of additional questions.
I downloaded again the 0.0.6 version, which has the
sv_assembly_mm2.py
sv_assembly_py
sv_caller.py
sv_processor.py
utils.py
breakmer.py

all in the root directory, with a drawimage folder with a draw_trl_plot.R
file.

The documentation for this here: http://ryanabo.github.io/BreaKmer/
does not seem to apply in the same way.

When I put in the command
python breakmer.py prepare_reference_data -c
/path/to/config/file/kmer_region.config

I get the following error

Usage: breakmer.py [options] <config file name>

breakmer.py: error: option -c: invalid integer value:

when I look at python breakmer.py --help

informs me that the -c option is to specify translocation threshold, not to
take a config file:

-c TRL_SR_THRESH, --trl_sr_thresh=TRL_SR_THRESH

```
                    Split read support threshold for translocations

                    [default: 2]
```

I attempted to drop the "-c", to put the relative path instead of the
absolute path, but this does not seem to work. (and I get different errors)

Thanks for your help,

Signy

**Comment by signy-chow** [comment]
I also tried using the breakmer.cfg ( prepare_reference_data --c
/path/to/config/breakmer.cfg) from the B2M example data set from the
previous version, which it will still not take

Also, do you have an example data file I can try this on?

Thank you!
Signy

Thanks!

**Comment by signy-chow** [comment]
Hi, again, Matt,

Are you able to clarify for me which version of breakmer I should be using?
Again, the 0.0.6b version, which has the
sv_assembly_mm2.py
sv_assembly_py
sv_caller.py
sv_processor.py
utils.py
breakmer.py

all in the root directory, with a drawimage folder with a draw_trl_plot.R
file. and runs everything at once

whereas the 0.0.6-ccgd version has these modularlized in separate folders
with the need to put in the prepare_reference_data, the start_blat_server
and the run commands separately.

I cannot get either of these versions to output a bamfile for the
translocation events for me.

Thanks,
Signy

**Comment by mducar** [comment]
Hi Signy,

The version of Breakmer you should use is under the "Releases" section.  You should use the latest release v0.0.6 called "CCGD_Profile_Production".  It sounds like you are cloning the repo and trying to run from there.

Thanks for pointing out the issue with the documentation.  The description at http://ryanabo.github.io/BreaKmer/ wasn't set up by our team and doesn't apply to the latest release.  We need to improve the documentation, but won't have the opportunity for a while.

-Matt
