### ISSUE TITLE
I meet another problem

### ISSUE THREAD

**Issue by DNA-language** [a-bioinformatician/BreaKmer#30]
err info :

`Traceback (most recent call last):
  File "../BreaKmer-master/breakmer.py", line 72, in <module>
    RUN_TRACKER.run()
  File "/ifs/TJPROJ3/RD/shanguangyu/project/BreaKmer-master/breakmer/processor/analysis.py", line 143, in run
    aggResults = analyze_targets(targetAnalysisList)
  File "/ifs/TJPROJ3/RD/shanguangyu/project/BreaKmer-master/breakmer/processor/analysis.py", line 79, in analyze_targets
    if not targetRegion.find_sv_reads():  # No SV reads extracted. Exiting.
  File "/ifs/TJPROJ3/RD/shanguangyu/project/BreaKmer-master/breakmer/processor/target.py", line 552, in find_sv_reads
    self.extract_bam_reads('sv')  # Extract variant reads.
  File "/ifs/TJPROJ3/RD/shanguangyu/project/BreaKmer-master/breakmer/processor/target.py", line 578, in extract_bam_reads
    self.variation.set_var_reads(sampleType, bamFile, self.chrom, self.start, self.end, self.regionBuffer)
  File "/ifs/TJPROJ3/RD/shanguangyu/project/BreaKmer-master/breakmer/processor/target.py", line 165, in set_var_reads
    pysam.sort(self.files['sv_bam'], self.files['sv_bam_sorted'].replace('.bam', ''))
  File "/ifs/TJPROJ3/RD/shanguangyu/software/python27/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/utils.py", line 75, in **call**
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\nUsage: samtools sort [options...] [in.bam]\nOptions:\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n  -n         Sort by read name\n  -o FILE    Write final output to FILE rather than standard output\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n  -@, --threads INT\n             Set number of sorting and compression threads [1]\n      --input-fmt-option OPT[=VAL]\n               Specify a single input file format option in the form\n               of OPTION or OPTION=VALUE\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n               Specify output format (SAM, BAM, CRAM)\n      --output-fmt-option OPT[=VAL]\n               Specify a single output file format option in the form\n               of OPTION or OPTION=VALUE\n      --reference FILE\n               Reference sequence FASTA FILE [null]\n'

it seems  get stuck when it invoke 'pysam' package which sort bam file, does anyone tells some usefull info  .   any opinoin is appreciate.

**Comment by mducar** [comment]
Hi,  

Based on the error messages, you are using the code from the master branch.  As mentioned in the Readme, this is development code and is not supported.

If you look in the "releases" section, there is a release tagged for version 0.0.6 of the software.  Please use that version:
https://github.com/ccgd-profile/BreaKmer/releases

Best,
Matt

**Comment by Tinalxt** [comment]
Hi~ I had the same problem, but when I run the example_data with version 0.0.6, I got  a new problem, just like below:
 1 Traceback (most recent call last):
  2   File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/breakmer.py", line 96, in <module>
  3     r.run(tic)
  4   File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/sv_processor.py", line 189, in run
  5     trgt.extract_bam_reads() # Extract the reads that provide evidence for structural variation.
  6   File "/Workspace/home/difanglei/pipeline/ctDNA/software/BreaKmer-0.0.6/sv_processor.py", line 537, in extract_bam_reads
  7     sort(self.files['sv_bam'],self.files['sv_bam_sorted'].replace('.bam',''))
  8 NameError: global name 'sort' is not defined

I wonder if it is a new bug? And how can I fix it. Thank you~
