### ISSUE TITLE
"reference_data" issue

### ISSUE THREAD

**Issue by fcgportal** [a-bioinformatician/BreaKmer#8]
Dear ‘BreaKmer’ developers, Thanks for developing ‘BreaKmer’! It is of a great interest for us to be able to discover gene translocation. We have downloaded BreaKmer package and example data. We used successfully got the output results of example data without any error. But we have an issue to product the special gene reference data. We checked the ref_seq folder from example data, and we have no idea how to product  "_15mers_counts_0" and "_15mers_dump" files. Would you please help us out? We would be very appreciable if you could advise us what could be amend in our procedure in order to perform a successful ‘BreaKmer’ run.

**Comment by ccgd-rnd** [comment]
Hi, thanks for trying out BreaKmer! It sounds like you tried to run BreaKmer using the example data and it worked successfully, but when you try it on other data you are having issues producing the reference data files? Could you please clarify what steps you went through and what the specific issues are at each step? If you could provide the exact command that was used and the config file that was used, that would be very helpful.

The reference kmer files are generated using the program jellyfish, and all of this should be handled by BreaKmer when it is initially run.

**Comment by ryanabo** [comment]
Hi, thanks for trying out BreaKmer! I apologize for the trouble in using it. Could you provide the exact steps that you have taken to run the program and also list out the issues at each of the steps? If you could provide the command line used to run it as well as the configuration file used, that would be very helpful. I can track down the issues from there. Thanks!
