### ISSUE TITLE
option to specify port for blat

### ISSUE THREAD

**Issue by jasper1918** [a-bioinformatician/BreaKmer#9]
Hi,

Congrats on putting together a great program for fusion detection.

I have been using breakmer on a server where the default option of blat 8000-9500 will not work because they are occupied or at least the random port is routinely hitting an occupied port.  Any chance you can add an option to specify the port number?

Thanks!

-Jeff

**Comment by ryanabo** [comment]
Hi Jeff,

Thanks for testing and using BreaKmer. I have added this feature in the master branch. You will just need to include the following in your configuration file:

'blat_port=<port number>' 

I have not tested it yet, so please let me know if it works (or not). 

Ryan

**Comment by jasper1918** [comment]
I'll give it a try and let you know.   Thanks for the quick fix!!

-Jeff

On Friday, May 15, 2015, Ryan Abo notifications@github.com wrote:

> Hi Jeff,
> 
> Thanks for testing and using BreaKmer. I have added this feature in the
> master branch. You will just need to include the following in your
> configuration file:
> 
> 'blat_port='
> 
> I have not tested it yet, so please let me know if it works (or not).
> 
> Ryan
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/a-bioinformatician/BreaKmer/issues/9#issuecomment-102553773
> .

## 

Jeff Jasper
(801) 372-2395

**Comment by jasper1918** [comment]
Its been awhile but just noticed this was left open. The fix worked as expected. Thanks!!

**Comment by ryanabo** [comment]
No problem, thanks for closing.
